# Generated by Django 5.0.2 on 2024-02-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('fam', models.CharField(max_length=255)),
                ('otc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('PEN', 'В работе'), ('ACC', 'Успешно'), ('REJ', 'Не принято')], max_length=3)),
                ('beauntyTitle', models.TextField()),
                ('title', models.TextField()),
                ('other_titles', models.TextField()),
                ('connect', models.TextField(blank=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('level_winter', models.CharField(max_length=255)),
                ('level_summer', models.CharField(max_length=255)),
                ('level_autumn', models.CharField(max_length=255)),
                ('level_spring', models.CharField(max_length=255)),
                ('coord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_data.coords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_data.users')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(max_length=255, upload_to='images/%Y/%m/%d')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval_data.perevaladded')),
            ],
        ),
    ]
