# Generated by Django 5.0.2 on 2024-02-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default=79999999999, max_length=11),
            preserve_default=False,
        ),
    ]
