# Generated by Django 5.0.2 on 2024-02-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_data', '0002_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новое'), ('PEN', 'В работе'), ('ACC', 'Успешно'), ('REJ', 'Не принято')], default='NEW', max_length=3),
        ),
    ]
