# Generated by Django 5.0.2 on 2024-02-27 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_data', '0003_alter_perevaladded_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='coord_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pereval_data.coords'),
        ),
    ]
