# Generated by Django 5.0.2 on 2024-02-29 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_data', '0005_alter_perevaladded_connect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='coord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_data.coords'),
        ),
    ]
